package com.example.sony.jizha.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.example.sony.jizha.Widget.BaseModel;

/**
 * Entity mapped to table "CHAT_MSG".
 */
public class ChatMsg implements BaseModel {

    //消息的类型
    //文本
    public static final int MSG_TYPE_TEXT = 1;
    //图片
    public static final int MSG_TYPE_IMG = 2;
    //声音
    public static final int MSG_TYPE_VOICE = 3;
    //视频
    public static final int MSG_TYPE_VIDEO = 4;


    //消息是否发送，判断listView中的布局用，发送跟接收的布局是不相同的
    //发送
    public static final int SEND = 0;
    //接收
    public static final int RECEVIER = 1;

    //消息的状态
    //未发送
    public static final int STATUS_NOSEND = 0;
    //发送成功
    public static final int STATUS_SEND_SUCCESS = 1;
    //发送失败
    public static final int STATUS_SEND_FAIL = 2;


    //已读
    public static final int STATUS_READED = 3;
    //未读
    public static final int STATUS_UNREAD = 4;

    private Long id;
    private long memberid;
    private long contactid;
    private String ChatMsg;
    /**
     * Not-null value.
     */
    private java.util.Date chattime;
    private int chattype;
    private int isreceive;
    private int status;

    public ChatMsg() {
    }

    public ChatMsg(Long id) {
        this.id = id;
    }

    public ChatMsg(Long id, long memberid, long contactid, String ChatMsg, java.util.Date chattime, int chattype, int isreceive, int status) {
        this.id = id;
        this.memberid = memberid;
        this.contactid = contactid;
        this.ChatMsg = ChatMsg;
        this.chattime = chattime;
        this.chattype = chattype;
        this.isreceive = isreceive;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMemberid() {
        return memberid;
    }

    public void setMemberid(long memberid) {
        this.memberid = memberid;
    }

    public long getContactid() {
        return contactid;
    }

    public void setContactid(long contactid) {
        this.contactid = contactid;
    }

    public String getChatMsg() {
        return ChatMsg;
    }

    public void setChatMsg(String ChatMsg) {
        this.ChatMsg = ChatMsg;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getChattime() {
        return chattime;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setChattime(java.util.Date chattime) {
        this.chattime = chattime;
    }

    public int getChattype() {
        return chattype;
    }

    public void setChattype(int chattype) {
        this.chattype = chattype;
    }

    public int getIsreceive() {
        return isreceive;
    }

    public void setIsreceive(int isreceive) {
        this.isreceive = isreceive;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "ChatMsg{" +
                "id=" + id +
                ", memberid=" + memberid +
                ", contactid=" + contactid +
                ", ChatMsg='" + ChatMsg + '\'' +
                ", chattime=" + chattime +
                ", chattype=" + chattype +
                ", isreceive=" + isreceive +
                ", status=" + status +
                '}';
    }
}
